/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package examen1_claudiohernandez;

import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Claudio Hernandez
 */
public class Examen1_ClaudioHernandez extends javax.swing.JFrame {

    /**
     * Creates new form Examen1_ClaudioHernandez
     */
    public Examen1_ClaudioHernandez() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tablas = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        autor = new javax.swing.JTextField();
        idioma = new javax.swing.JTextField();
        titulo = new javax.swing.JTextField();
        editorial = new javax.swing.JTextField();
        genero = new javax.swing.JTextField();
        anioEscribio = new com.toedter.calendar.JDateChooser();
        anioEntroALibreria = new com.toedter.calendar.JDateChooser();
        jButton1 = new javax.swing.JButton();
        Nombre = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        nombre1 = new javax.swing.JTextField();
        apellido = new javax.swing.JTextField();
        codigo = new javax.swing.JTextField();
        edad = new javax.swing.JTextField();
        usuario = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabla2 = new javax.swing.JTable();
        buscarTexto1 = new javax.swing.JTextField();
        cajaAutor = new javax.swing.JTextField();
        cajaTitulo = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        botonautor = new javax.swing.JButton();
        botonco = new javax.swing.JButton();
        botontitulo = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        buscarTexto = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        tomarPrestado = new javax.swing.JButton();
        buscar = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        tabla1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tablas.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                tablasStateChanged(evt);
            }
        });

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "autor", "titulo", "genero", "editorial", "idioma", "Año de creacion", "Año de  ingreso a la libreria", "codigo", "Estado", "Nombre de pestamista", "Codigo persona"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabla);

        jButton2.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jButton2.setText("eliminar");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jButton3.setText("modificar");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(405, 405, 405)
                .addComponent(jButton2)
                .addGap(380, 380, 380)
                .addComponent(jButton3)
                .addContainerGap(811, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addContainerGap(76, Short.MAX_VALUE))
        );

        tablas.addTab("inventario", jPanel2);

        jLabel2.setText("autor");

        jLabel3.setText("genero");

        jLabel4.setText("anio de Publicacion");

        jLabel5.setText("anio de entrada a la libreria");

        jLabel6.setText("titulo de libro");

        jLabel8.setText("idioma");

        jLabel10.setText("editorial");

        jButton1.setText("agregarLibro");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(58, 58, 58)
                        .addComponent(editorial, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel4Layout.createSequentialGroup()
                                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel2))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(anioEscribio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(autor, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                                        .addComponent(genero)))
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(anioEntroALibreria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel6))
                                .addGap(35, 35, 35)
                                .addComponent(idioma, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(361, 361, 361)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1257, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(22, 22, 22)
                        .addComponent(jLabel3)
                        .addGap(31, 31, 31)
                        .addComponent(jLabel4))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(autor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(genero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(anioEscribio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(26, 26, 26)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(anioEntroALibreria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(titulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(editorial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(68, 68, 68)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(idioma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 134, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(84, 84, 84))
        );

        tablas.addTab("agregar libros", jPanel4);

        jLabel14.setText("Nombre");

        jLabel15.setText("primer apellido");

        jLabel16.setText("codigo");

        jLabel18.setText("edad");

        usuario.setText("Iniciar sesion como usuario");
        usuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                usuarioMouseClicked(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jButton5.setText("Iniciar sesion como administrador");
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel20.setText("Si eres admin preisona el boton para iniciar sesion como administrador");

        jLabel21.setText("Llena los datos de usuario antes de ingresar");

        javax.swing.GroupLayout NombreLayout = new javax.swing.GroupLayout(Nombre);
        Nombre.setLayout(NombreLayout);
        NombreLayout.setHorizontalGroup(
            NombreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NombreLayout.createSequentialGroup()
                .addGroup(NombreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(NombreLayout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(NombreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel18)
                            .addComponent(jLabel17)
                            .addComponent(jLabel16)
                            .addComponent(jLabel15)
                            .addComponent(jLabel14))
                        .addGap(96, 96, 96)
                        .addGroup(NombreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(nombre1, javax.swing.GroupLayout.DEFAULT_SIZE, 259, Short.MAX_VALUE)
                            .addComponent(apellido)
                            .addGroup(NombreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(codigo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE)
                                .addComponent(edad, javax.swing.GroupLayout.Alignment.LEADING)))
                        .addGroup(NombreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(NombreLayout.createSequentialGroup()
                                .addGap(179, 179, 179)
                                .addComponent(jLabel20))
                            .addGroup(NombreLayout.createSequentialGroup()
                                .addGap(386, 386, 386)
                                .addComponent(jButton5))))
                    .addGroup(NombreLayout.createSequentialGroup()
                        .addGap(176, 176, 176)
                        .addComponent(usuario))
                    .addGroup(NombreLayout.createSequentialGroup()
                        .addGap(154, 154, 154)
                        .addComponent(jLabel21)))
                .addContainerGap(530, Short.MAX_VALUE))
        );
        NombreLayout.setVerticalGroup(
            NombreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NombreLayout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(NombreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(nombre1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(NombreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(apellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5))
                .addGap(65, 65, 65)
                .addGroup(NombreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(codigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(NombreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(NombreLayout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jLabel18)
                        .addGap(15, 15, 15))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, NombreLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                        .addComponent(edad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(jLabel17)
                .addGap(93, 93, 93)
                .addComponent(jLabel21)
                .addGap(18, 18, 18)
                .addComponent(usuario)
                .addGap(150, 150, 150))
        );

        tablas.addTab("Login", Nombre);

        tabla2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "autor", "titulo", "genero", "editorial", "idioma", "Año de creacion", "Año de  ingreso a la libreria", "codigo", "Estado", "Nombre de pestamista", "Codigo persona"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tabla2);

        jLabel12.setText("Codigo del libro");

        jLabel13.setText("Autor del libro");

        jLabel19.setText("Titulo del libro");

        botonautor.setText("buscar por autor");
        botonautor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonautorMouseClicked(evt);
            }
        });

        botonco.setText("busar por codigo");
        botonco.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botoncoMouseClicked(evt);
            }
        });

        botontitulo.setText("buscar por titulo");
        botontitulo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botontituloMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 1774, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(119, 119, 119)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13)
                    .addComponent(jLabel19))
                .addGap(178, 178, 178)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cajaAutor, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                    .addComponent(cajaTitulo)
                    .addComponent(buscarTexto1))
                .addGap(117, 117, 117)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonautor)
                    .addComponent(botonco)
                    .addComponent(botontitulo))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(buscarTexto1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(botonco)
                        .addGap(19, 19, 19)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cajaAutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(botonautor))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cajaTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19)
                    .addComponent(botontitulo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        tablas.addTab("Buscar en inventario", jPanel1);

        buscarTexto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarTextoActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel9.setText("Busqueda de llbros");

        jLabel11.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel11.setText("Ingresa el codigoo del libro que quieres pedir prestado");

        tomarPrestado.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        tomarPrestado.setText("tomar prestado");
        tomarPrestado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tomarPrestadoMouseClicked(evt);
            }
        });

        buscar.setText("Buscar");
        buscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buscarMouseClicked(evt);
            }
        });

        tabla1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "autor", "titulo", "genero", "editorial", "idioma", "Año de creacion", "Año de  ingreso a la libreria", "codigo", "Estado", "Nombre de pestamista", "Codigo persona"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane4.setViewportView(tabla1);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(jLabel11)
                        .addGap(81, 81, 81)
                        .addComponent(buscarTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(92, 92, 92)
                        .addComponent(buscar))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(403, 403, 403)
                        .addComponent(jLabel9))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 1178, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(361, 361, 361)
                        .addComponent(tomarPrestado, javax.swing.GroupLayout.PREFERRED_SIZE, 454, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel9)
                .addGap(28, 28, 28)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(buscarTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buscar))
                .addGap(17, 17, 17)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tomarPrestado)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        tablas.addTab("pedir prestado", jPanel3);

        tablas.setSelectedIndex(2);

        jLabel1.setBackground(new java.awt.Color(51, 51, 255));
        jLabel1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 204));
        jLabel1.setText("Libreria claudio");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(487, 487, 487)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(tablas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tablas, javax.swing.GroupLayout.PREFERRED_SIZE, 666, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(52, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        inventarioLibros.add(new libros(autor.getText(), titulo.getText(), genero.getText(), editorial.getText(), idioma.getText(), anioEscribio.getDate(), anioEntroALibreria.getDate()));
        DefaultTableModel modelo = (DefaultTableModel) tabla.getModel();
        Object[] x = {
            inventarioLibros.get(inventarioLibros.size() - 1).getAutor(), inventarioLibros.get(inventarioLibros.size() - 1).getTitulo(),
            inventarioLibros.get(inventarioLibros.size() - 1).getGenero(), inventarioLibros.get(inventarioLibros.size() - 1).getEditoriales(),
            inventarioLibros.get(inventarioLibros.size() - 1).getIdioma(), inventarioLibros.get(inventarioLibros.size() - 1).getAnioEscribio(),
            inventarioLibros.get(inventarioLibros.size() - 1).getAnioEntroALibreria(), inventarioLibros.get(inventarioLibros.size() - 1).getCodigoISBN(),
            inventarioLibros.get(inventarioLibros.size() - 1).getEstadoLibro(), inventarioLibros.get(inventarioLibros.size() - 1).getNombreAprestado(), inventarioLibros.get(inventarioLibros.size() - 1).getCodigodePersona()
        };
        modelo.addRow(x);
        tabla.setModel(modelo);

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        if (tabla.getSelectedRow() >= 0) {
            DefaultTableModel modelo
                    = (DefaultTableModel) tabla.getModel();
            modelo.removeRow(tabla.getSelectedRow());
            tabla.setModel(modelo);
            //tf_edad_maxima.setText(maxima_edad());
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2MouseClicked

    private void buscarTextoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarTextoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buscarTextoActionPerformed

    private void buscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buscarMouseClicked
        DefaultTableModel modelo = (DefaultTableModel) tabla1.getModel();
        /* if (cajaTitulo != null) {
            String txtT = cajaTitulo.getText();
            for (int i = 0; i < inventarioLibros.size(); i++) {
                if (txtT.equals(inventarioLibros.get(i).getTitulo())) {
                    modelo.addRow(hacerTabla(i));

                }
            }
        } else if (cajaAutor!=null) {
            String txtA = cajaAutor.getText();
            for (int i = 0; i < inventarioLibros.size(); i++) {
                if (txtA.equals(inventarioLibros.get(i).getAutor())) {
                    modelo.addRow(hacerTabla(i));

                }
            }
        } else*/ if (buscarTexto != null) {
            String txt = buscarTexto.getText();
            for (int i = 0; i < inventarioLibros.size(); i++) {
                if (txt.equals(inventarioLibros.get(i).getCodigoISBN())) {
                    modelo.addRow(hacerTabla(i));

                }
            }
        }
        buscarTexto.setText("");
        // cajaAutor.setText("");
        // cajaTitulo.setText("");
        tabla1.setModel(modelo);

        // TODO add your handling code here:
    }//GEN-LAST:event_buscarMouseClicked

    private void usuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usuarioMouseClicked
        usuario1.setApellido(apellido.getText());
        usuario1.setNombre(nombre1.getText());
        usuario1.setCodigo(codigo.getText());
        usuario1.setEdad((Integer.parseInt(edad.getText())));
        UsuarioActual = usuario1;
        if (UsuarioActual instanceof usuarios) {
            cajaAutor.setEditable(false);
            cajaAutor.setEditable(false);
            buscarTexto1.setEditable(false);
            autor.setEditable(false);
            titulo.setEnabled(false);
            genero.setEditable(false);
            editorial.setEditable(false);
            idioma.setEditable(false);
            anioEscribio.setEnabled(false);
            anioEntroALibreria.setEnabled(false);
            JOptionPane.showMessageDialog(this, "Ha iniciado sesion como un usuario normal, algunas funciones estan desabilitadas");
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_usuarioMouseClicked

    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked
        JOptionPane.showMessageDialog(this, "Has iniciado sesion como administrador");
        UsuarioActual = usuario2;
        if (UsuarioActual instanceof admin) {
            cajaAutor.setEditable(true);
            cajaAutor.setEditable(true);
            buscarTexto1.setEditable(true);
            autor.setEditable(true);
            titulo.setEnabled(true);
            genero.setEditable(true);
            editorial.setEditable(true);
            idioma.setEditable(true);
            anioEscribio.setEnabled(true);
            anioEntroALibreria.setEnabled(true);

        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5MouseClicked

    private void tomarPrestadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tomarPrestadoMouseClicked
        if (tabla1.getSelectedRow() >= 0) {
            selec = tabla1.getSelectedRow();
            DefaultTableModel modelo
                    = (DefaultTableModel) tabla1.getModel();

            if (UsuarioActual instanceof usuarios) {
                String txt = ((String) (modelo.getValueAt(tabla1.getSelectedRow(), 0)));
                for (int i = 0; i < inventarioLibros.size(); i++) {
                    if (txt.equals(inventarioLibros.get(i).getAutor())) {
                        if (inventarioLibros.get(i).getEstadoLibro().equals("Disponible")) {
                            ((usuarios) UsuarioActual).getLibrosPrestados().add(
                                    new libros(inventarioLibros.get(i).getAutor(), inventarioLibros.get(i).getTitulo(), inventarioLibros.get(i).getGenero(), inventarioLibros.get(i).getEditoriales(), inventarioLibros.get(i).getIdioma(), inventarioLibros.get(i).getAnioEscribio(), inventarioLibros.get(i).getAnioEntroALibreria()));
                            inventarioLibros.get(i).setEstadoLibro("prestado");
                            inventarioLibros.get(i).setCodigodePersona(((usuarios) UsuarioActual).getCodigo());
                            inventarioLibros.get(i).setNombreAprestado(((usuarios) UsuarioActual).getNombre());

                            ((usuarios) UsuarioActual).getHistorial().add(
                                    new libros(inventarioLibros.get(i).getAutor(), inventarioLibros.get(i).getTitulo(), inventarioLibros.get(i).getGenero(), inventarioLibros.get(i).getEditoriales(), inventarioLibros.get(i).getIdioma(), inventarioLibros.get(i).getAnioEscribio(), inventarioLibros.get(i).getAnioEntroALibreria()));
                        } else {
                            JOptionPane.showMessageDialog(this, "Libro no disponible");
                        }

                        break;
                    }
                }
            }

        }

        // TODO add your handling code here:
    }//GEN-LAST:event_tomarPrestadoMouseClicked

    private void tablasStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_tablasStateChanged
        if (tablas.getSelectedIndex() == 0) {
           JOptionPane.showMessageDialog(this, "INVENTARIO");

            DefaultTableModel modelo = (DefaultTableModel) tabla.getModel();
            if (selec >= 0) {
                if (inventarioLibros.size()>selec) {
                   /* Object[] x = {
                    inventarioLibros.get(selec).getAutor(), inventarioLibros.get(selec).getTitulo(),
                    inventarioLibros.get(selec).getGenero(), inventarioLibros.get(selec).getEditoriales(),
                    inventarioLibros.get(selec).getIdioma(), inventarioLibros.get(selec).getAnioEscribio(),
                    inventarioLibros.get(selec).getAnioEntroALibreria(), inventarioLibros.get(selec).getCodigoISBN(),
                    inventarioLibros.get(selec).getEstadoLibro(), inventarioLibros.get(selec).getNombreAprestado(), inventarioLibros.get(selec).getCodigodePersona()
                };
                    */
                modelo.setValueAt(inventarioLibros.get(selec).getEstadoLibro(),selec, 8);
            modelo.setValueAt(inventarioLibros.get(selec).getNombreAprestado(),selec, 9);
            modelo.setValueAt(inventarioLibros.get(selec).getCodigodePersona(),selec, 10);
                }
                
                
                
            }

        }

        // TODO add your handling code here:
    }//GEN-LAST:event_tablasStateChanged

    private void botonautorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonautorMouseClicked
        DefaultTableModel modelo = (DefaultTableModel) tabla2.getModel();

        if (!cajaAutor.equals(null)) {
            String txtA = cajaAutor.getText();
            for (int i = 0; i < inventarioLibros.size(); i++) {
                if (txtA.equals(inventarioLibros.get(i).getAutor())) {
                    modelo.addRow(hacerTabla(i));

                }
            }
        }

        tabla2.setModel(modelo);

        cajaAutor.setText("");
        // TODO add your handling code here:
    }//GEN-LAST:event_botonautorMouseClicked

    private void botontituloMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botontituloMouseClicked
        DefaultTableModel modelo = (DefaultTableModel) tabla2.getModel();

        String txtT = cajaTitulo.getText();
        for (int i = 0; i < inventarioLibros.size(); i++) {
            if (txtT.equals(inventarioLibros.get(i).getTitulo())) {
                modelo.addRow(hacerTabla(i));

            }
        }
        tabla2.setModel(modelo);
        cajaTitulo.setText("");
        buscarTexto1.setText("");

        // TODO add your handling code here:
    }//GEN-LAST:event_botontituloMouseClicked

    private void botoncoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botoncoMouseClicked
        DefaultTableModel modelo = (DefaultTableModel) tabla2.getModel();

        String txt = buscarTexto1.getText();
        for (int i = 0; i < inventarioLibros.size(); i++) {
            if (txt.equals(inventarioLibros.get(i).getCodigoISBN())) {
                modelo.addRow(hacerTabla(i));

            }

        }
        tabla2.setModel(modelo);
        buscarTexto1.setText("");

        // TODO add your handling code here:
    }//GEN-LAST:event_botoncoMouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        if (tabla.getSelectedRow() >= 0) {
            DefaultTableModel modelo
                    = (DefaultTableModel) tabla.getModel();

            String autor1 = JOptionPane.showInputDialog("nuevo autor");
            String titulo1 = JOptionPane.showInputDialog("nuevo titulo");
            String genero1 = JOptionPane.showInputDialog("nuevo genero");
            String editorial1 = JOptionPane.showInputDialog("nuevo editorial");
            String idioma1 = JOptionPane.showInputDialog("nuevo idioma");
            //String x = JOptionPane.showInputDialog("nuevo mes");
            modelo.setValueAt(autor1,tabla.getSelectedRow(), 0);
            modelo.setValueAt(titulo1,tabla.getSelectedRow(), 1);
            modelo.setValueAt(genero1,tabla.getSelectedRow(), 2);
            modelo.setValueAt(editorial1,tabla.getSelectedRow(), 3);
            modelo.setValueAt(idioma1,tabla.getSelectedRow(), 4);
            tabla.setModel(modelo);
            //tf_edad_maxima.setText(maxima_edad());
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3MouseClicked
    public static Object[] hacerTabla(int i) {//============================================================
        Object[] x = {
            inventarioLibros.get(i).getAutor(), inventarioLibros.get(i).getTitulo(),
            inventarioLibros.get(i).getGenero(), inventarioLibros.get(i).getEditoriales(),
            inventarioLibros.get(i).getIdioma(), inventarioLibros.get(i).getAnioEscribio(),
            inventarioLibros.get(i).getAnioEntroALibreria(), inventarioLibros.get(i).getCodigoISBN(), inventarioLibros.get(selec).getEstadoLibro(),
            inventarioLibros.get(selec).getNombreAprestado(), inventarioLibros.get(selec).getCodigodePersona()
        };
        return x;

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        JOptionPane.showMessageDialog(null, "Dirigete a login para empezar");
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows Classic".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Examen1_ClaudioHernandez.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Examen1_ClaudioHernandez.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Examen1_ClaudioHernandez.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Examen1_ClaudioHernandez.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Examen1_ClaudioHernandez().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Nombre;
    private com.toedter.calendar.JDateChooser anioEntroALibreria;
    private com.toedter.calendar.JDateChooser anioEscribio;
    private javax.swing.JTextField apellido;
    private javax.swing.JTextField autor;
    private javax.swing.JButton botonautor;
    private javax.swing.JButton botonco;
    private javax.swing.JButton botontitulo;
    private javax.swing.JButton buscar;
    private javax.swing.JTextField buscarTexto;
    private javax.swing.JTextField buscarTexto1;
    private javax.swing.JTextField cajaAutor;
    private javax.swing.JTextField cajaTitulo;
    private javax.swing.JTextField codigo;
    private javax.swing.JTextField edad;
    private javax.swing.JTextField editorial;
    private javax.swing.JTextField genero;
    private javax.swing.JTextField idioma;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextField nombre1;
    private javax.swing.JTable tabla;
    private javax.swing.JTable tabla1;
    private javax.swing.JTable tabla2;
    private javax.swing.JTabbedPane tablas;
    private javax.swing.JTextField titulo;
    private javax.swing.JButton tomarPrestado;
    private javax.swing.JButton usuario;
    // End of variables declaration//GEN-END:variables
       static ArrayList<libros> inventarioLibros = new ArrayList();
    static usuarios usuario1 = new usuarios();
    static admin usuario2 = new admin();
    static Object UsuarioActual;
    static int selec;

}
